# Generated by Django 4.2.5 on 2023-09-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=255, verbose_name='Nome do Cliente')),
                ('endereco_cliente', models.CharField(max_length=255, verbose_name='Endereço do Cliente')),
                ('email_cliente', models.EmailField(max_length=255, verbose_name='Email do Cliente')),
                ('telefone_cliente', models.CharField(max_length=15, verbose_name='Telefone do Cliente')),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
    ]
