# Generated by Django 4.1.5 on 2023-09-22 20:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor da Venda')),
                ('data_venda', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Data da Venda')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_venda', to='cliente.cliente')),
            ],
            options={
                'db_table': 'venda',
            },
        ),
    ]
